#!/usr/bin/env bash
set -e
echo "=== Studio test path (hosted, no Docker) ==="
echo "Requires: .env.local with GENLAYER_PRIVATE_KEY (or use Studio UI without key)"
echo "Study: https://studio.genlayer.com"
echo ""
echo "Option A — Studio UI (no CLI):"
echo "  1. Open https://studio.genlayer.com"
echo "  2. Create new contract -> paste contracts/provedown.py"
echo "  3. Run: register_sla('demo-healthy','https://example.com','https://<your-worker>/bundle?preset=no_breach','{\"p95_threshold\":2000,\"error_threshold\":0.01,\"fill_threshold\":0.80,\"match_threshold\":0.85}')"
echo "  4. Run: request_attestation('demo-healthy') -> verdict NO_BREACH"
echo "  5. Run: request_attestation('demo-breach') [preset breach] -> BREACH"
echo ""
echo "Option B — CLI to studionet (needs genlayer account):"
echo "  genlayer network set studionet"
echo "  genlayer account import --name provedown-deployer --private-key \$GENLAYER_PRIVATE_KEY   # if not yet"
echo "  genlayer account use provedown-deployer"
echo "  genlayer deploy --contract ./contracts/provedown.py --network studionet"
echo "  # note address -> set NEXT_PUBLIC_PROVEDOWN_CONTRACT_ADDRESS in .env.local"
echo "  genlayer call <address> get_sla --args '[\"demo-healthy\"]' --network studionet"
